apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault 

---

apiVersion: v1
kind: Secret
metadata:
  name: vault-k8s-auth-secret
  annotations:
    kubernetes.io/service-account.name: vault
type: kubernetes.io/service-account-token

---

apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: "pg-secret"
spec:
  path: "/database/creds/readonly"
  method: "GET"
  provider:
    server: "http://vault.vault.svc.cluster.local:8200"
    auth:
      kubernetes:
        mountPath: "kubernetes"
        role: "readonly"
        serviceAccountRef:
          name: "vault"

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "pg-secret-com"
spec:
  refreshInterval: "2m"
  target:
    name: pg-secret-com
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: "pg-secret"
